### ISSUE TITLE
TypeError: "curFilter" is read-only

### ISSUE THREAD

**Issue by januszm** [clhenrick/React-Leaflet-demo#1]
For some reason it does NOT happen (error message) in your code, however you also use React 0.14.x where props should be already immutable.

I'm trying to reproduce your approach to filtering map results but in my code the line:

``` javascript
this.props.curFilter = this.state.filter;
```

is causing the error in the title of this issue. I'm suprised that it does not do so in your code as you also assign a value to `this.props.curFilter` which should be immutable.

**Comment by clhenrick** [comment]
@januszm thanks for the heads up, I'll make a change or feel free to submit a PR.

**Comment by januszm** [comment]
Thanks for quick reply, I'm still wondering why I don't see this error in FF console while running your code. I'm not sure if we should simply remove that line or find a workaround. It seems that after removing it the app will work properly.

**Comment by clhenrick** [comment]
It's the React way to not update a prop that's passed to a child component from within the child component so I'm all for removing that line. Not sure why I put it there in the first place! 

I'll make the change momentarily.
